[workspace]
members = [
    "gdsfx-app",
    "gdsfx-audio",
    "gdsfx-build",
    "gdsfx-data",
    "gdsfx-library",
]
resolver = "2"

[workspace.dependencies]
# TODO
# this list can be organized into categories
# instead of just being sorted alphabetically
anyhow = "1.0.79"
base64 = "0.21.6"
build_script = "0.2.0"
crossbeam-channel = "0.5.11"
derivative = "2.2.0"
directories = "5.0.1"
educe = "0.5.11"
eframe = "0.25.0"
egui-modal = "0.3.2"
flate2 = "1.0.28"
lazy_static = "1.4.0"
once_cell = "1.19.0"
parking_lot = "0.12.1"
prettyplease = "0.2.16"
proc-macro2 = "1.0.76"
quote = "1.0.35"
reqwest = { version = "0.11.23", features = ["blocking"] }
rodio = "0.17.3"
rust-i18n = "2.3.0"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
strum = { version = "0.25.0", features = ["derive"] }
syn = "2.0.48"
url = "2.5.0"
winapi = { version = "0.3.9", features = ["wincon", "winuser"] }
