[package]
name = "gd_sfx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.5"
eframe = "0.24.1"
flate2 = "1.0.28"
reqwest = { version = "0.11.23", features = ["blocking"] }
slab_tree = "0.3.2"
