[package]
name = "gdsfx"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "gdsfx-app",
    "gdsfx-audio",
    "gdsfx-build",
    "gdsfx-files",
    "gdsfx-library",
]
resolver = "2"

[workspace.dependencies]
# Workspace crates
gdsfx-app = { path = "gdsfx-app" }
gdsfx-audio = { path = "gdsfx-audio" }
gdsfx-build = { path = "gdsfx-build" }
gdsfx-files = { path = "gdsfx-files" }
gdsfx-library = { path = "gdsfx-library" }

# Utilities
ahash = "0.8.7"
anyhow = "1.0.79"
educe = "0.5.11"
lazy_static = "1.4.0"
once_cell = "1.19.0"
parking_lot = "0.12.1"
pretty-bytes = "0.2.2"
rayon = "1.8.0"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
strum = { version = "0.25.0", features = ["derive"] }

[dependencies]
gdsfx-app = { workspace = true }

anyhow = { workspace = true }

winapi = { version = "0.3.9", features = ["wincon"] }

[profile.release]
opt-level = 'z'
lto = true
strip = "symbols"
