[package]
name = "gd_sfx"
version = "0.1.0"
edition = "2021"
build = "build/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.5"
crossbeam-channel = "0.5.10"
eframe = "0.25.0"
egui-modal = "0.3.2"
flate2 = "1.0.28"
lazy_static = "1.4.0"
pretty-bytes = "0.2.2"
reqwest = { version = "0.11.23", features = ["blocking"] }
rodio = "0.17.3"
slab_tree = "0.3.2"
strum = { version = "0.25.0", features = ["derive"] }
rust-i18n = "2.3.0"
rayon = "1.8.0"

[build-dependencies]
build_script = "0.2.0"
serde_json = "1.0.111"
quote = "1.0.35"
proc-macro2 = "1.0.76"
prettyplease = "0.2.16"
syn = "2.0.48"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3.9", features = ["wincon", "winuser"] }
