[package]
name = "gdsfx-app"
description = "The main GDSFX crate which runs the application."
version = "0.1.0"
edition = "2021"
build = "build/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = { workspace = true }
anyhow = { workspace = true }
educe = { workspace = true }
eframe = { workspace = true }
egui-modal = { workspace = true }
egui_extras = { workspace = true }
gdsfx-audio = { path = "../gdsfx-audio" }
gdsfx-build = { path = "../gdsfx-build" }
gdsfx-files = { path = "../gdsfx-files" }
gdsfx-library = { path = "../gdsfx-library" }
once_cell = { workspace = true }
pretty-bytes = { workspace = true }
rayon = { workspace = true }
rust-i18n = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { workspace = true }

[build-dependencies]
ahash = { workspace = true }
anyhow = { workspace = true }
gdsfx-build = { path = "../gdsfx-build" }
gdsfx-files = { path = "../gdsfx-files" }
quote = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
image = { workspace = true }
