on:
  # debug build
  push:
    branches: "**"
  pull_request: 
    types:
      - opened
      - edited

  # release build
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
            extra_files: gdsfx-audio/include/windows/fmod.dll
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz tar.zst
          - target: x86_64-apple-darwin
            archive: zip
    steps:
      # dependencies for the linux build
      - run:
          sudo apt-get -y install libglib2.0-dev
          sudo apt-get -y install pkg-config
          sudo apt-get -y install libssl-dev
          sudo apt-get -y install libatk1.0-0
          sudo apt-get -y install libgtk-3-dev

      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          EXTRA_FILES: ${{ matrix.extra_files }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
          TOOLCHAIN_VERSION: nightly
          UPLOAD_MODE: ${{ github.event_name == 'release' && 'release' || 'none' }}
